<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Food>
 */
class ProductFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $foodProductNames = [
            'Spaghetti Carbonara',
            'Margherita Pizza',
            'Grilled Cheese Sandwich',
            'Chicken Caesar Salad',
            'Beef Tacos',
            'Vegetarian Burrito',
            'Salmon Sushi',
            'Miso Soup',
            'Cheeseburger',
            'Buffalo Wings',
            'BBQ Ribs',
            'Eggplant Parmesan',
            'Pad Thai',
            'Chicken Alfredo',
            'Seafood Paella',
            'Falafel Wrap',
            'Lamb Gyro',
            'Clam Chowder',
            'Pancakes with Maple Syrup',
            'Chocolate Brownie',
            'Apple Pie',
            'Strawberry Cheesecake',
            'Banana Bread',
            'Croissant',
            'Avocado Toast',
            'Vegetable Stir Fry',
            'Chicken Fried Rice',
            'Beef Stroganoff',
            'Lasagna',
            'Shrimp Scampi',
            'Caesar Salad',
            'Tuna Salad',
            'Chicken Noodle Soup',
            'French Onion Soup',
            'Garlic Bread',
            'Bruschetta',
            'Caprese Salad',
            'Mango Smoothie',
            'Blueberry Muffins',
            'Oatmeal Cookies',
            'Cinnamon Rolls',
            'Pumpkin Pie',
            'Fish and Chips',
            'Beef Wellington',
            'Quiche Lorraine',
            'Stuffed Bell Peppers',
            'Chicken Fajitas',
            'Margarita',
            'Creme Brulee',
            'Moussaka',
            'Baklava',
            'Gulab Jamun',
            'Peking Duck',
            'Dim Sum',
            'Pho',
            'Ramen',
            'Bibimbap',
            'Tiramisu',
            'Gelato',
            'Panini',
            'Prosciutto and Melon',
            'Pasta Primavera',
            'Chicken Parmesan',
            'Pulled Pork Sandwich',
            'Beef Brisket',
            'Samosa',
            'Naan Bread',
            'Curry Chicken',
            'Biryani',
            'Hummus and Pita',
            'Tzatziki',
            'Spanakopita',
            'Stuffed Grape Leaves',
            'Feta Cheese Salad',
            'Mozzarella Sticks',
            'Chili Con Carne',
            'Mac and Cheese',
            'Roast Beef',
            'Mashed Potatoes',
            'Green Bean Casserole',
            'Cornbread',
            'Buttermilk Biscuits',
            'Cranberry Sauce',
            'Deviled Eggs',
            'Roasted Brussels Sprouts',
            'Cauliflower Rice',
            'Mango Salsa',
            'Pico de Gallo',
            'Guacamole',
            'Churros',
            'Flan',
            'Custard Tart',
            'Key Lime Pie',
            'Pecan Pie',
            'Fudge Brownies',
            'Salted Caramel Ice Cream',
            'Peach Cobbler',
            'Blackberry Jam',
            'Gingerbread Cookies',
            'Pomegranate Salad',
            'Watermelon Feta Salad',
            'Roasted Pumpkin Seeds',
            'Carrot Cake',
            'Lemon Bars',
            'Meringue Pie',
            'Coconut Macaroons',
        ];

        return [
            'name' => $this->faker->randomElement($foodProductNames),
            'price' => fake()->randomFloat(2, 1, 100),
            'quantity' => fake()->numberBetween(1, 100),
            'image' => 'https://source.unsplash.com/random/400x300/?food',
            'description' => fake()->text(),
            'seller' => fake()->numberBetween(1, 100),
        ];
    }
}
